### ISSUE TITLE
Import errors while trying to run file "run.sh"

### ISSUE THREAD

**Issue by yasuo19** [HazyResearch/snorkel-superglue#17]
run.sh: line 7: [: ==: unary operator expected
run.sh: line 9: [: ==: unary operator expected
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from superglue_tasks import cb, copa, multirc, rte, wic, wsc, swag
  File "C:\Users\\###\Desktop\snorkel-superglue\superglue_tasks\__init__.py", line 1, in <module>
    from . import cb, copa, multirc, rte, wic, wsc, swag, semcor
ImportError: cannot import name 'semcor'

**So, commented semcor in "__init__.py" and faced this error:**

Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from superglue_slices import slice_func_dict
  File "C:\Users\\###\Desktop\snorkel-superglue\superglue_slices\__init__.py", line 1, in <module>
    from . import general_sfs, RTE_sfs, WiC_sfs, CB_sfs, COPA_sfs, MultiRC_sfs, WSC_sfs
  File "C:\Users\\###\Desktop\snorkel-superglue\superglue_slices\CB_sfs.py", line 1, in <module>
    from slicing.slicing_function import slicing_function
ModuleNotFoundError: No module named 'slicing'

Also, the slicing_function in sf.py contains **PASS** .

**Upon importing the slicing_function from sf.py, I get the following error:**
Traceback (most recent call last):
  File "run.py", line 28, in <module>
    from superglue_slices import slice_func_dict
  File "C:\Users\####\Desktop\snorkel-superglue\superglue_slices\__init__.py", line 1, in <module>
    from . import general_sfs, RTE_sfs, WiC_sfs, CB_sfs, COPA_sfs, MultiRC_sfs, WSC_sfs
  File "C:\Users\####\Desktop\snorkel-superglue\superglue_slices\CB_sfs.py", line 64, in <module>
    slice_func_dict = {slice.__name__: slice for slice in slices}
  File "C:\Users\####\Desktop\snorkel-superglue\superglue_slices\CB_sfs.py", line 64, in <dictcomp>
    slice_func_dict = {slice.__name__: slice for slice in slices}
AttributeError: 'slicing_function' object has no attribute '__name__'

Any idea on how to fix the import errors?

**Comment by bhancock8** [comment]
Thanks for bringing this to our attention! It looks like a file using an older API snuck into the commit. The broken imports and missing attribute were fixed by #18 and #19, and we added a Travis CI test #20 to make sure that we'll be made aware of any future breakages. 

Note that the setup instructions have also changed, as you can now just pip install the `snorkel-superglue` tag of the `snorkel` repo. This repo will be updated to use the updated major release of snorkel (v0.9) that's coming in August, but it should work now as well.
